### PR TITLE
Make "preset" input optional

### PR DESCRIPTION
**Pull request by YevheniiSemendiak**
If not specified - the smallest one will be used.

### CODE REVIEW

**Comment by YevheniiSemendiak** [comment]
It feels like the implementation is a (potential) bug usage, but I'm not sure.

Context:
- we have a neuro-flow action with a parameterized `preset` name (via inputs), where the [default](https://github.com/neuro-actions/jupyter/blob/ys/licence_and_preset/action.yml#L10) value is an empty string.
- if in the parent flow we do not specify this input in args, the preset name will be the first one available in the list (flow [defaults](https://github.com/neuro-actions/jupyter/blob/ys/licence_and_preset/.neuro/live.yaml#L6) are ignored, check it by pulling the branch and running `neuro-flow run jupyter`).

@asvetlov, is it a bug? If yes, then where? (1) neuro-flow does not pass defaults into hosted on GH actions, (2) one is allowed to specify the preset as an empty string.

**Comment by asvetlov** [comment]
First-in-presets-list is the default preset.
Maybe we did not document it in neuro-cli somewhere but we for sure discussed this behavior many times offline on our daily meetings.

**Comment by asvetlov** [comment]
Empty string for a preset is not supported IMHO but maybe de-facto it works as default.
Please check and confirm.
It the statement is true -- I suggest just documenting it (and maybe add a test to never break the behavior).

**Comment by YevheniiSemendiak** [comment]
>Empty string for a preset is not supported IMHO but maybe de-facto it works as default.
Please check and confirm.

Yes, if we set an empty string ("") to the preset name, the first-in-presets-list is used.

>First-in-presets-list is the default preset.

But what about the [flow.defaults](https://github.com/neuro-actions/jupyter/blob/ys/licence_and_preset/.neuro/live.yaml#L4)? Or it works only for jobs, defined directly on the flow, but not used as actions?

**Comment by asvetlov** [comment]
If preset is not set and there is not flow default preset -- the system-default preset is used.
Which is the first preset returned by `neuro config show` list

**Comment by YevheniiSemendiak** [comment]
>If preset is not set and there is not flow default preset -- the system-default preset is used.

That is the problem, try to run the example from the current [branch](https://github.com/neuro-actions/jupyter/blob/ys/licence_and_preset/.neuro/live.yaml):
- it has a default.preset set to [cpu-medium](https://github.com/neuro-actions/jupyter/blob/ys/licence_and_preset/.neuro/live.yaml#L6) (second in the list on neuro-compute cluster).
- the action preset is set to an empty string. (it is missed in the list of args in the parent flow description and the [default](https://github.com/neuro-actions/jupyter/blob/ys/licence_and_preset/action.yml#L10) value is "")

According to the description, we expect the jupyter job to run on cpu-medium (flow default preset), but actually, it is the cpu-small (the system default preset).

**Comment by asvetlov** [comment]
Got you finally.
No, action cannot look into defaults.
For this situation 'optional' preset probably doesn't work; you need to pass it explicitly.

**Comment by YevheniiSemendiak** [comment]
Ok, got you! Thanks for the explanation!
Closing this PR, no need to confuse the users.

**Pull request closed without merging**
